db: crm
server:
  port: 80
  servlet:
    #    context-path: /shengsiit
    session:
      cookie:
        name: SSCRM
spring:
  profiles:
    active: dev
    include: druid,mybatisplus,shiro
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://129.204.70.43:3306/${db}?useUnicode=true&characterEncoding=UTF-8&userSSL=false&tinyIntlisBit=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: crm_group23
    password: Group23@2019
